import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/Components/Navbar";
import {Toaster} from "react-hot-toast";
import {Provider} from "jotai";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar />
          {children}
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
