apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: 579924771643.dkr.ecr.ap-south-1.amazonaws.com/websocket:ccd4f3c
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: websocket-env-volume
              mountPath: /src/.env
              subPath: .env
      volumes:
        - name: websocket-env-volume
          configMap:
            name: websocket-config