apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      serviceAccountName: codebuild-sa
      containers:
        - name: websocket
          image: 717279689524.dkr.ecr.ap-south-1.amazonaws.com/websocket:067f095
          ports:
            - containerPort: 8080
